<a href="https://colab.research.google.com/github/rvoljanin/neuraluniversity/blob/master/notebooks/math/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [41]:
vector = np.array([1,2,3,4])
vector_defined = vector.reshape((1,4))
vector_vertical = vector.reshape((4,1))

print(vector)
print(vector_defined)
print(vector_vertical)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [42]:
def print_vector(v):
  shape = v.shape
  s = ''

  if len(shape) == 0:
    s = str(v)
  elif len(shape) == 1:
    for i in v:
      s += str(i) + '  '
  else:
    if shape[0] == 1:
      for i in range(shape[1]):
        s += str(v[0][i]) + '  '
    elif shape[1] == 1:
      for i in range(shape[0]):
        s += str(v[i][0]) + '\n'
      
  print(s)

print_vector(vector)
print_vector(vector_defined)
print_vector(vector_vertical)

1  2  3  4  
1  2  3  4  
1
2
3
4



In [45]:
print_vector(vector + 1)
print_vector(vector_vertical + 1)

print_vector(vector * 3)
print_vector(vector_vertical * 3)

2  3  4  5  
2
3
4
5

3  6  9  12  
3
6
9
12



In [46]:
vector2 = vector * 3
vector_vertical2 = vector_vertical + 7

print_vector(vector2)
print_vector(vector_vertical2)

3  6  9  12  
8
9
10
11



In [48]:
print_vector(vector + vector2)
print_vector(vector_vertical * vector_vertical2)

4  8  12  16  
8
18
30
44



In [52]:
matrix = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])
matrix2 = np.array([[145, 23, 191], [17, 252, 31], [99, 112, 39]])

print(matrix)
print(matrix2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[145  23 191]
 [ 17 252  31]
 [ 99 112  39]]


In [53]:
def print_matrix(m):
  for v in m:
    print_vector(v)

print_matrix(matrix)
print_matrix(matrix2)

0  1  2  
1  2  3  
2  3  4  
145  23  191  
17  252  31  
99  112  39  


In [56]:
print('Сложение')
print_matrix(matrix + 1)
print('Умножение')
print_matrix(matrix * 3)

Сложение
1  2  3  
2  3  4  
3  4  5  
Умножение
0  3  6  
3  6  9  
6  9  12  


In [57]:
print('Сложение')
print_matrix(matrix + matrix2)
print('Умножение')
print_matrix(matrix * matrix2)

Сложение
145  24  193  
18  254  34  
101  115  43  
Умножение
0  23  382  
17  504  93  
198  336  156  
