<a href="https://colab.research.google.com/github/rvoljanin/neuraluniversity/blob/master/notebooks/math/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [41]:
vector = np.array([1,2,3,4])
vector_defined = vector.reshape((1,4))
vector_vertical = vector.reshape((4,1))

print(vector)
print(vector_defined)
print(vector_vertical)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [42]:
def print_vector(v):
  shape = v.shape
  s = ''

  if len(shape) == 0:
    s = str(v)
  elif len(shape) == 1:
    for i in v:
      s += str(i) + '  '
  else:
    if shape[0] == 1:
      for i in range(shape[1]):
        s += str(v[0][i]) + '  '
    elif shape[1] == 1:
      for i in range(shape[0]):
        s += str(v[i][0]) + '\n'
      
  print(s)

print_vector(vector)
print_vector(vector_defined)
print_vector(vector_vertical)

1  2  3  4  
1  2  3  4  
1
2
3
4

