<a href="https://colab.research.google.com/github/rvoljanin/neuraluniversity/blob/master/notebooks/math/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [41]:
vector = np.array([1,2,3,4])
vector_defined = vector.reshape((1,4))
vector_vertical = vector.reshape((4,1))

print(vector)
print(vector_defined)
print(vector_vertical)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [42]:
def print_vector(v):
  shape = v.shape
  s = ''

  if len(shape) == 0:
    s = str(v)
  elif len(shape) == 1:
    for i in v:
      s += str(i) + '  '
  else:
    if shape[0] == 1:
      for i in range(shape[1]):
        s += str(v[0][i]) + '  '
    elif shape[1] == 1:
      for i in range(shape[0]):
        s += str(v[i][0]) + '\n'
      
  print(s)

print_vector(vector)
print_vector(vector_defined)
print_vector(vector_vertical)

1  2  3  4  
1  2  3  4  
1
2
3
4



In [45]:
print_vector(vector + 1)
print_vector(vector_vertical + 1)

print_vector(vector * 3)
print_vector(vector_vertical * 3)

2  3  4  5  
2
3
4
5

3  6  9  12  
3
6
9
12



In [46]:
vector2 = vector * 3
vector_vertical2 = vector_vertical + 7

print_vector(vector2)
print_vector(vector_vertical2)

3  6  9  12  
8
9
10
11



In [48]:
print_vector(vector + vector2)
print_vector(vector_vertical * vector_vertical2)

4  8  12  16  
8
18
30
44



In [52]:
matrix = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])
matrix2 = np.array([[145, 23, 191], [17, 252, 31], [99, 112, 39]])

print(matrix)
print(matrix2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[145  23 191]
 [ 17 252  31]
 [ 99 112  39]]


In [53]:
def print_matrix(m):
  for v in m:
    print_vector(v)

print_matrix(matrix)
print_matrix(matrix2)

0  1  2  
1  2  3  
2  3  4  
145  23  191  
17  252  31  
99  112  39  


In [56]:
print('Сложение')
print_matrix(matrix + 1)
print('Умножение')
print_matrix(matrix * 3)

Сложение
1  2  3  
2  3  4  
3  4  5  
Умножение
0  3  6  
3  6  9  
6  9  12  


In [57]:
print('Сложение')
print_matrix(matrix + matrix2)
print('Умножение')
print_matrix(matrix * matrix2)

Сложение
145  24  193  
18  254  34  
101  115  43  
Умножение
0  23  382  
17  504  93  
198  336  156  


In [0]:
def prod_matrix(m1, m2):
  shape1 = m1.shape
  shape2 = m2.shape

  if shape1[0] != shape2[1]:
    return np.array([])

  out_matrix = np.zeros((shape1[0], shape2[1]))

  for i in range(shape1[0]):
    for j in range(shape2[1]):
      curr_cell = 0
      for t in range(shape1[1]):
        curr_cell += m1[i,t] * m2[t,j]
      out_matrix[i,j] = curr_cell
  
  return out_matrix

In [62]:
matrix3 = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]])
matrix4 = np.array([[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]])

print('Первая матрица')
print_matrix(matrix3)
print('Вторая матрица')
print_matrix(matrix4)
print('Произведение')
print_matrix(prod_matrix(matrix3,matrix4))

Первая матрица
0  1  2  
1  2  3  
2  3  4  
3  4  5  
Вторая матрица
0  1  2  3  
1  2  3  4  
2  3  4  5  
Произведение
5.0  8.0  11.0  14.0  
8.0  14.0  20.0  26.0  
11.0  20.0  29.0  38.0  
14.0  26.0  38.0  50.0  


In [81]:
print('Перемножение трёх матриц')


def prod_3matrix(m1,m2,m3):
  return prod_matrix(m1,prod_matrix(m2,m3))

matrix6 = prod_3matrix(matrix3,matrix3,matrix4)

print_matrix(matrix6)

Перемножение трёх матриц
30.0  54.0  78.0  102.0  
54.0  96.0  138.0  180.0  
78.0  138.0  198.0  258.0  
102.0  180.0  258.0  336.0  


In [82]:
print('Разница между наибольшим и наименьшим элементами матрицы')

def min_max_diff(m):
  min = m[0][0]
  max = m[0][0]

  for i in range(m.shape[0]):
    for j in range(m.shape[1]):
      if m[i][j] < min:
        min = m[i][j]
      if m[i][j] > max:
        max = m[i][j]
  
  return max - min

print_matrix(matrix2)
print(min_max_diff(matrix2))

Разница между наибольшим и наименьшим элементами матрицы
145  23  191  
17  252  31  
99  112  39  
235


In [94]:
def transpose_matrix(matrix):
  shape = matrix.shape
  
  out_matrix = np.zeros((shape[1], shape[0]))
  
  for i in range(shape[0]):
    for j in range(shape[1]):
      out_matrix[j,i] = matrix[i,j]
  
  return out_matrix

def prod_matrix_self(m):
  prod = prod_matrix(m,transpose_matrix(m))
  try:
    return np.linalg.inv(prod)
  except np.linalg.LinAlgError:
    return np.array([])

print('Обычная матрица')
print_matrix(prod_matrix_self(matrix2))
print('Сингулярная матрица')
print_matrix(prod_matrix_self(matrix3))

Обычная матрица
4.922161299950098e-05  3.5827282686054585e-05  -9.699256905166802e-05  
3.5827282686054585e-05  6.742477571208759e-05  -0.00012450592780287138  
-9.6992569051668e-05  -0.00012450592780287138  0.0003033103696888382  
Сингулярная матрица
